services:
  - type: web
    name: fraud-dashboard
    env: python
    runtime : python3.10
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard/app.py --server.port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    plan: free